/*
 * This source file was generated by the Gradle 'init' task
 */
package nz.co.bibble.ktmcptest

import kotlinx.coroutines.runBlocking
import nz.co.bibble.ktmcptest.di.appModule
import nz.co.bibble.ktmcptest.hueclient.HueClient
import org.koin.core.context.startKoin
import org.koin.java.KoinJavaComponent.getKoin
import org.slf4j.Logger
import org.slf4j.LoggerFactory

fun main() {
    // Create a logger instance
    val logger: Logger = LoggerFactory.getLogger("Main")

    // Log application startup
    logger.info("Starting application...")

    // Start Koin
    startKoin { modules(appModule) }

    // Retrieve the HueClient instance
    val hueClient: HueClient = getKoin().get()

    runBlocking {
        // Get all lights
        val lights = hueClient.getLights()

        logger.debug("Received lights: $lights")

        // Turn on the first light
        val firstLight = lights.firstOrNull()
        if (firstLight != null) {
            // Turn on first light and Set brightness of the first light to 200
            hueClient.setLightState(firstLight.id, true, 200.0, null, null, null)
        }
    }

    logger.info("Application finished.")
}
